import "./globals.scss";
import "katex/dist/katex.min.css";
import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import { Cutive_Mono as FontMono } from "next/font/google";
import { Inter_Tight as FontSans } from "next/font/google";
import { Playfair_Display as FontSerif } from "next/font/google";
import { MainHeader } from "@/components/main-header";
import { MainFooter } from "@/components/main-footer";
import Scene, { SceneView } from "@/components/scene";
import { CatSprite, CatView } from "@/components/cat-sprite";

const fontMono = FontMono({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-mono",
});

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSerif = FontSerif({
  subsets: ["latin"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(fontSerif.variable, fontMono.variable, fontSans.variable)}
    >
      <body className={cn("min-h-screen bg-background antialiased")}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <MainHeader />
          <div id="main-content" className="relative pb-16">
            <Scene className="absolute inset-0" />
            <CatView className="absolute inset-0" />
            {children}
          </div>
          <MainFooter />
        </ThemeProvider>
      </body>
    </html>
  );
}
